/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.shed.lab.computable_future;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class ComputablefutureTest {
	@Test
	public void appHasAGreeting() {
		assertNotNull("app should have a greeting", "not null");
	}
}
